version: "3"

services:
  postgres-compose:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "postgresql"
      POSTGRES_DB: "todoapp"
    ports:
      - "5440:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    external: true